### ISSUE TITLE
Unable to use SwitchReactor

### ISSUE THREAD

**Issue by bdavies01** [strongback/strongback-java#62] opened 2016-02-09 23:17 UTC
When we try to use SwitchReactor, it doesn't seem to call the command at all.

`protected SwitchReactor reactor = Strongback.switchReactor();`
We set up the SwitchReactor one time as: 
`reactor.onTriggered(input.getDriveStick().getTrigger(), () -> Strongback.submit(new ToggleGears(this)));`

The command itself has been verified to be working when being manually submitted to the Strongback queue, so the lambda function is not being called as far as we can tell. This did not work with a direct print to the console nor using a direct command with a lambda function. This failed both with MockFlightSticks that we wrote and forcefully triggered, and with real joysticks on the robot as well.

**Comment by rhauch** [comment] 2016-02-09 23:20
@bdavies01: is this the same as #60? If so, then this is a duplicate.

**Comment by bdavies01** [comment] 2016-02-09 23:30
Sorry, we didn't realize that `SwitchReactor` was of type `AsyncSwitchReactor` and assumed this was a different issue. Do you have an estimated fix-time or suggested work-around? Our current plan is to repeatedly check Joystick values during an update cycle.

**Comment by xortive** [comment] 2016-02-10 02:23
My open pull request that references #60 fixes AsyncSwitchReactor

**Comment by rhauch** [comment] 2016-02-10 14:43
Closing as a duplicate of #60.

**Closed as completed by rhauch** 2016-02-10 14:43 UTC
